// ✅ V00330: REGISTRO AUTOMÁTICO del Historial de Cambios.
//   Este archivo viaja CON el código: cada entrega de versión añade aquí su
//   entrada, así el módulo "Historial de Cambios" se actualiza SOLO al
//   publicar — sin capturar nada a mano. Las entradas manuales (Firestore)
//   se combinan con estas; si una versión se registra a mano, la manual manda.
//   Formato de fecha: aaaa-mm-dd. La hora es opcional.

export interface CambioApp {
  fecha: string;
  hora?: string;
  version: string;
  titulo: string;
  resumen: string;   // explicación cotidiana (la que se copia para WhatsApp)
  detalle?: string;  // detalle técnico opcional
}

export const CAMBIOS_APP: CambioApp[] = [
  { fecha: '2026-09-25', hora: '14:30', version: 'V00361', titulo: 'Agregar saldo con puente desplegable', resumen: 'En Saldos de Puentes el saldo se agrega desde un solo botón arriba, con el puente elegido en lista desplegable (moneda no editable, saldo pendiente y total en vivo); las tarjetas de cada puente quedan solo informativas, con su botón de historial.' },
  { fecha: '2026-09-25', hora: '13:30', version: 'V00360', titulo: 'Peaje al marcar Verde y gasto del día en la tarjeta', resumen: 'El peaje se descuenta al marcar Verde MX (exportación, Puente III en pesos) o Verde USA (importación, Caseta AVI en dólares) en los horarios; la tarjeta de Operaciones muestra lo gastado hoy en cruces en dólares y en pesos, y su botón Actualizar saldo abre el modal con puente (lista del catálogo), moneda, saldo a agregar, saldo pendiente por puente y total.' },
  { fecha: '2026-09-25', hora: '12:00', version: 'V00359', titulo: 'Saldo disponible por moneda e historial de deducciones', resumen: 'Saldos de Puentes muestra arriba el saldo disponible en dólares y en pesos; al presionarlos (o el 📜 de cada puente) se abre el historial por fechas de deducciones y recargas con el saldo corrido. El modal de recarga de Operaciones ahora muestra fecha, moneda, saldo a agregar, saldo restante y total por puente.' },
  { fecha: '2026-09-25', hora: '10:30', version: 'V00358', titulo: 'Cuentas de puentes: saldo inicial, cruces y saldo actual', resumen: 'Saldos de Puentes funciona ahora como cuenta por puente: Agregar saldo suma recargas (fecha de hoy y moneda fijas, con saldo restante y total en el modal), cada operación completada descuenta su cruce, y el saldo actual se marca en amarillo o rojo al ir quedando bajo — en el módulo y en la tarjeta del resumen.' },
  { fecha: '2026-09-24', hora: '12:00', version: 'V00357', titulo: 'Utilidad Transfer en la ficha y saldo de puente retroactivo', resumen: 'La ficha de la operación muestra la UTILIDAD cuando es Transfer (generado − saldo del puente − gastos adicionales − sueldo del proveedor, con desglose y pesos convertidos con el TC de la operación), y Saldos de Puentes trae el botón Aplicar a operaciones para colocar el saldo del puente a todas las completadas que no lo tenían.' },
  { fecha: '2026-09-24', hora: '13:00', version: 'V00356', titulo: 'Utilidad de Transfer con puente y gastos, y saldos masivos', resumen: 'En Transfer, la Utilidad Estimada resta ahora el saldo del puente y los gastos además del proveedor (todo en MXN con el TC de la operación); y el botón Saldos de puentes de Servicios Completados coloca el saldo a todas las completadas que no lo tenían.' },
  { fecha: '2026-09-24', hora: '10:30', version: 'V00355', titulo: 'Tarifa del puente al completar el servicio', resumen: 'Al marcar Servicio Completado, la operación guarda la tarifa del puente del día: Importación toma el saldo de Caseta AVI y Exportación el de Caseta Puente III. Además la moneda queda marcada con su color en Saldos de Puentes y la tarjeta avisa si falta la captura de hoy.' },
  { fecha: '2026-09-23', hora: '21:40', version: 'V00354', titulo: 'Cliente (Mercancía) con razón social', resumen: 'El buscador de Cliente (Mercancía) del formulario muestra y guarda la razón social de la empresa (no el nombre corto), y con ello la razón social aparece en la operación y en todos los documentos.' },
  { fecha: '2026-09-23', hora: '21:00', version: 'V00353', titulo: 'Razón social en los documentos generados', resumen: 'Los documentos de la operación (Solicitud de Retiro, Check List, Instrucciones de Servicio y demás) muestran ahora la RAZÓN SOCIAL de los clientes y proveedores — el cliente de la mercancía incluido — tomada de la ficha de la empresa.' },
  { fecha: '2026-09-23', hora: '20:00', version: 'V00352', titulo: 'Saldo precargado al elegir el puente y captura una vez al día', resumen: 'Al elegir el puente en Saldos de Puentes, el saldo se precarga con el monto del catálogo; y la captura desde la tarjeta de Operaciones guarda en la tabla con la fecha del momento y el botón se oculta cuando el día ya quedó registrado.' },
  { fecha: '2026-09-23', hora: '19:30', version: 'V00351', titulo: 'El registro de saldos de puentes abre en modal', resumen: 'En Saldos de Puentes, el botón Registrar saldo (y el editar de cada fila) abre ahora un modal con la fecha, el puente y el saldo, en vez del formulario en el encabezado.' },
  { fecha: '2026-09-23', hora: '19:00', version: 'V00350', titulo: 'Módulo Saldos de Puentes (Bases de Datos)', resumen: 'Nuevo módulo en Bases de Datos para registrar cada día el saldo de los puentes: fecha, puente (relacionado con el catálogo Tipos de Gastos) y saldo. La tarjeta Casetas del día también alimenta esta tabla, y el saldo más reciente actualiza el catálogo para toda la app.' },
  { fecha: '2026-09-23', hora: '18:10', version: 'V00349', titulo: 'Casetas del día en el resumen, con captura de saldos', resumen: 'La tarjeta Casetas del día ya aparece en el resumen junto al diésel, con el saldo vigente del Puente AVI y del Puente III, y su botón + Actualizar saldos abre la captura (como el tipo de cambio): lo guardado va al catálogo Tipos de Gastos y se refleja en toda la app al momento.' },
  { fecha: '2026-09-23', hora: '17:30', version: 'V00348', titulo: 'Casetas del día en el resumen', resumen: 'El resumen del día muestra ahora la tarjeta Casetas del día con el saldo vigente del Puente AVI y del Puente III, tomado en vivo del catálogo Tipos de Gastos: al editar el importe ahí, la tarjeta se actualiza al momento.' },
  { fecha: '2026-09-23', hora: '16:45', version: 'V00347', titulo: 'Convenios sin prefijo de ningún tipo', resumen: 'El botón Quitar CONV- ahora también elimina el número inicial que quedaba en algunos nombres de convenio ("285 - Cruce…" queda "Cruce…"), en operaciones y en los detalles de convenios de clientes y proveedores. Vuelve a presionarlo una vez.' },
  { fecha: '2026-09-23', hora: '16:00', version: 'V00346', titulo: 'Convenios sin el prefijo CONV-', resumen: 'Los convenios de clientes y proveedores ya no llevan el prefijo CONV-: los nuevos nacen solo con su número, y el botón Quitar CONV- de Detalles del Convenio se lo quita a todos los registrados (convenios y operaciones), conservando los números.' },
  { fecha: '2026-09-23', hora: '15:00', version: 'V00345', titulo: 'Los documentos de la operación abren en su modal', resumen: 'El botón Ver documentos de la ficha abre ahora un modal centrado con todos los documentos de la operación, cada uno con su botón Ver/Descargar.' },
  { fecha: '2026-09-23', hora: '14:30', version: 'V00344', titulo: 'Ver documentos en la ficha, editar la vista y Manual del módulo', resumen: 'La ficha de la operación tiene el botón Ver documentos con TODO lo subido (Carta Porte, DODA, Entry\'s, Manifiesto y más); el botón ✎ Vista permite ocultar/mostrar los botones agregados (guardado para todos); y el botón 📖 Manual abre la guía del módulo en otra pestaña.' },
  { fecha: '2026-09-23', hora: '13:20', version: 'V00343', titulo: 'Razón Social de la empresa en toda la cadena', resumen: 'La empresa tiene ahora el campo Razón Social: captúralo (ej. en Caro-Kar Pesos pon Caro-Kar Transportes), presiona el botón Razón social de Empresas y todas las operaciones, facturas y pagos mostrarán ese nombre.' },
  { fecha: '2026-09-23', hora: '12:30', version: 'V00342', titulo: 'Moneda visible al editar la empresa + razón social en toda la cadena', resumen: 'La moneda y el tipo de factura de la empresa aparecen de inmediato al editar (aunque estén guardados con el nombre viejo), y el nuevo botón Razón social escribe el nombre actual de todas las empresas en operaciones, facturación y pagos.' },
  { fecha: '2026-09-23', hora: '10:00', version: 'V00341', titulo: 'Los documentos de la operación ya se consultan', resumen: 'Los PDF que subes a una operación (Carta Porte, DODA, Entry\'s, etc.) ahora se ven donde los necesitas: en la pestaña Pedimento del formulario aparece la lista de documentos guardados, y el detalle de la operación en la auditoría también los muestra.' },
  { fecha: '2026-09-22', hora: '18:20', version: 'V00340', titulo: 'Auditar operaciones desde Estadísticas + Excel con configuraciones', resumen: 'En el reporte de operaciones de Estadísticas cada fila trae ver detalle y editar (el cambio se refleja al momento), y el Excel abre primero el selector de columnas con configuraciones guardadas con nombre.' },
  { fecha: '2026-09-22', hora: '17:00', version: 'V00339', titulo: 'Estadísticas EN VIVO', resumen: 'Las estadísticas quedaron suscritas a la base: cualquier cambio en operaciones, facturación o pagos se refleja al momento, sin volver a presionar Buscar — los números siempre coinciden con lo que muestra el resto de la app.' },
  { fecha: '2026-09-22', hora: '16:10', version: 'V00338', titulo: 'Configuraciones del Excel con nombre (Servicios Completados)', resumen: 'Al exportar a Excel primero se muestran las configuraciones guardadas: eliges una y arma el Excel con sus columnas, o creas una nueva, le pones nombre y queda guardada para todos.' },
  { fecha: '2026-09-22', hora: '09:30', version: 'V00337', titulo: 'Reportes "todos excepto" y minimizado informativo', resumen: 'En Reportes ya puedes incluir todos los estatus EXCEPTO los que marques; y al minimizar una operación, la pastilla muestra la referencia, el cliente, el remolque, la fecha de servicio y el tipo de operación.' },
  { fecha: '2026-09-21', hora: '20:10', version: 'V00335', titulo: 'Rango de fechas y moneda en la auditoría por empresa', resumen: 'La auditoría de la empresa ahora filtra las operaciones por rango de fecha de servicio y muestra la moneda configurada en la ficha de la empresa.' },
  { fecha: '2026-09-21', hora: '19:20', version: 'V00334', titulo: 'Auditoría de la cadena por EMPRESA', resumen: 'Desde la ficha de cualquier empresa (botón 🔍) se ve toda su cadena en vivo — operaciones, facturación y pagos — separada por su papel: Cliente que Paga, Cliente de Mercancía o Proveedor de transporte y servicios.' },
  { fecha: '2026-09-21', hora: '18:40', version: 'V00332', titulo: 'Combustible y Catálogos bajo Autorizaciones', resumen: 'Se integraron Combustible y Catálogos al módulo de Autorizaciones: en Combustible se controlan sus campos y acciones, y en Catálogos quién puede crear, editar o borrar registros de cualquier catálogo.' },
  { fecha: '2026-09-21', hora: '17:05', version: 'V00331', titulo: 'La autorización solo mira lo que tú tocas', resumen: 'Al guardar una empresa, la autorización se revisa únicamente sobre los campos que el usuario realmente modificó; lo que el formulario recalcula solo ya no dispara avisos ni afecta a los demás campos.' },
  { fecha: '2026-09-21', hora: '16:45', version: 'V00330', titulo: 'El historial de cambios se llena solo', resumen: 'Cada actualización de la app queda registrada automáticamente en el Historial de Cambios, con fecha, versión y su explicación — ya no hay que capturarla a mano.' },
  { fecha: '2026-09-21', version: 'V00329', titulo: 'Módulo Historial de Cambios + escritura corregida en Empresas', resumen: 'Se estrenó el módulo Historial de Cambios para la gerencia (con informe copiable para WhatsApp) y se corrigió que algunos campos de Empresas perdieran el cursor al escribir.' },
  { fecha: '2026-09-21', version: 'V00328', titulo: 'Autorización solo si de verdad se modificó', resumen: 'Al guardar una empresa ya no pide autorización por campos que nadie tocó; solo por lo que sí se cambió.' },
  { fecha: '2026-09-21', version: 'V00327', titulo: 'Los campos protegidos se ven bloqueados', resumen: 'En Empresas, los campos que requieren autorización aparecen atenuados con candado 🔒; al darles clic se solicita el acceso temporal.' },
  { fecha: '2026-09-21', version: 'V00326', titulo: 'Regla "Agregar libre" en Autorizaciones', resumen: 'Ahora un campo protegido puede capturarse libremente la PRIMERA vez (ej. la Moneda al crear la empresa) y quedar bloqueado para cambios posteriores.' },
  { fecha: '2026-09-21', version: 'V00325', titulo: 'Reporte de Vencimiento bajo Autorizaciones', resumen: 'Cambiar documentos o fechas del Reporte de Vencimiento ya no es libre: si el usuario no está autorizado, el cambio se convierte en una solicitud que un Admin aprueba.' },
  { fecha: '2026-09-20', version: 'V00324', titulo: 'Auditoría: rango de fechas, edición al frente y detalle legible', resumen: 'La auditoría filtra las operaciones por fecha de servicio, el formulario de edición abre al frente (y la auditoría te espera donde ibas) y el ojito muestra el detalle con nombres, no claves.' },
  { fecha: '2026-09-20', version: 'V00323', titulo: 'Auditoría más grande, con ✓ Revisado y caminos', resumen: 'La auditoría ocupa el 80% de la pantalla; cada pieza tiene botón ✓ Revisado (los revisados se van al final, los problemas al inicio) y al hacer clic en una operación, factura o pago se muestra SOLO su camino.' },
  { fecha: '2026-09-19', version: 'V00322', titulo: 'Auditoría en vivo, con detalle y edición', resumen: 'La auditoría quedó conectada en vivo: cualquier corrección se refleja al momento; cada pieza tiene ver detalle y editar, se resaltan los problemas y las monedas que no concuerdan.' },
  { fecha: '2026-09-19', version: 'V00320', titulo: 'Auditoría en tres columnas con monedas', resumen: 'La auditoría se ve en tres columnas (Operaciones, Facturación, Pagos) con las monedas de cada pieza a la vista y el camino de cada operación iluminado.' },
  { fecha: '2026-09-19', version: 'V00319', titulo: 'La auditoría busca solo clientes que pagan', resumen: 'El buscador de la auditoría ya no lista todas las empresas: solo los clientes que pagan.' },
  { fecha: '2026-09-19', version: 'V00318', titulo: 'Nueva Auditoría de la cadena por cliente', resumen: 'Se estrenó la auditoría que cruza operaciones, facturas y pagos de un cliente: detecta operaciones que cambiaron después de facturarse, sin facturar, dobles cobros y pagos descuadrados, con Excel del reporte.' },
  { fecha: '2026-09-19', version: 'V00317', titulo: 'Reparar nombres con CONV + Excel completo por empresa', resumen: 'Botón para limpiar los nombres que traían el "CONV-###" incrustado, y descarga de un Excel por empresa con sus operaciones, facturación y pagos en tres hojas.' },
  { fecha: '2026-09-18', version: 'V00316', titulo: 'Los módulos ya no se desordenan al recargar', resumen: 'Se corrigió que la app se viera desacomodada al recargar justo después de publicarse una actualización.' },
  { fecha: '2026-09-18', version: 'V00315', titulo: 'Unir duplicados con toda la información', resumen: 'Al unir registros duplicados de empresas se ve la ficha de cada candidato (tipos, RFC, status, fecha de alta y operaciones) antes de decidir cuál queda.' },
  { fecha: '2026-09-18', version: 'V00314', titulo: 'Nombres de convenio limpios y clientes bien distinguidos', resumen: 'Los convenios ya no muestran el "CONV-###" en el nombre y el buscador de Cliente (Paga) distingue empresas con el mismo nombre.' },
  { fecha: '2026-09-18', version: 'V00313', titulo: 'Tarifas A/B y catálogos en vivo en operaciones', resumen: 'El modal de operaciones muestra el número de tarifario correcto, deja elegir Tarifa A o B en convenios con dos montos, y los convenios y tarifarios se actualizan en vivo mientras el formulario está abierto.' },
  { fecha: '2026-09-17', version: 'V00312', titulo: 'Abrir en pestaña nueva con filtros + tablas más ágiles', resumen: 'Convenios, tarifarios y cancelados abren en pestaña nueva conservando los filtros; las tablas grandes cargan por partes y las barras de desplazamiento siempre se ven.' },
  { fecha: '2026-09-17', version: 'V00311', titulo: 'Corregido el error al abrir en pestaña nueva tras publicar', resumen: 'Se corrigió el error que a veces salía al abrir "Ver en nueva pestaña" justo después de publicarse una actualización.' },
];
